$.CONTROL_LAYER_NAMES = [
  "edit",
  "edit color",
  "edit colors",
  "edit control",
  "color",
  "colors",
  "color control",
  "color controls",
  "control",
  "controls",
  "controller",
  "settings",
  "setting",
  "scene settings",
];

$.CONTROL_EFFECT_MATCH_NAMES = [
  "ADBE Color Control",
  "ADBE Slider Control",
  "ADBE Checkbox Control",
  "ADBE Angle Control",
  "ADBE Point Control",
  "ADBE Point3D Control",
];

$.PREMIERE_PRO_EFFECTS = [
  "ADBE Basic 3D",
  "ADBE Gaussian Blur",
  "ADBE Gaussian Blur 2",
  "ADBE Motion Blur",
  "ADBE Drop Shadow",
  "ADBE Invert",
  "ADBE Lumetri",
  "ADBE Mosaic",
  "ADBE Noise2",
  "ADBE Offset",
  "ADBE Tint",
  "ADBE Color Balance (HLS)",
  "Mettle SkyBox Blur",
  "Mettle SkyBox Color Gradients",
  "Mettle SkyBox Digital Glitch",
  "Mettle SkyBox Glow",
  "Mettle SkyBox Sharpen",
  "ADBE SubspaceStabilizer",
  "ADBE Extract",
  "ADBE Find Edges",
  "ADBE Easy Levels2",
  "ADBE Brightness & Contrast 2",
  "ADBE Reduce Interlace Flicker",
  "ADBE Black&White",
  "ProcAmp",
  "ADBE Sharpen",
  "ADBE Timecode",
  "Cross Dissolve",
  "ADBE Block Dissolve",
  "ADBE Gradient Wipe",
  "ADBE Linear Wipe",
  "ADBE Radial Wipe",
  "ADBE Venetian Blinds",
  "ADBE Roughen Edges",
  "ADBE Color Emboss",
  "ADBE Emboss",
  "ADBE Corner Pin",
  "ADBE Fast Blur", // fast blur legacy
  "ADBE Spherize",
  "ADBE Turbulent Displace",
  "ADBE Wave Warp",
  "ADBE Geometry2", // transform
  "ADBE Twirl",
  "ADBE Magnify",
  "ADBE Mirror",
  "ADBE Arithmetic",
  "ADBE Checkerboard",
  "ADBE Ramp",
  "ADBE 4ColorGradient",
  "ADBE Posterize Time",
  "ADBE Circle",
  "ADBE CHANNEL MIXER",
  "ADBE Grid",
  "ADBE Paint Bucket",
];

$.DAVINCI_RESOLVE_EFFECTS = [
  "ADBE Basic 3D",
  "ADBE Gaussian Blur",
  "ADBE Gaussian Blur 2",
  "ADBE Motion Blur",
  "ADBE Drop Shadow",
  "ADBE Invert",
  "ADBE Lumetri",
  "ADBE Mosaic",
  "ADBE Noise2",
  "ADBE Offset",
  "ADBE Tint",
  "ADBE Color Balance (HLS)",
  "Mettle SkyBox Blur",
  "Mettle SkyBox Color Gradients",
  "Mettle SkyBox Digital Glitch",
  "Mettle SkyBox Glow",
  "Mettle SkyBox Sharpen",
  "ADBE SubspaceStabilizer",
  "ADBE Extract",
  "ADBE Find Edges",
  "ADBE Easy Levels2",
  "ADBE Brightness & Contrast 2",
  "ADBE Reduce Interlace Flicker",
  "ADBE Black&White",
  "ProcAmp",
  "ADBE Sharpen",
  "ADBE Timecode",
  "Cross Dissolve",
  "ADBE Block Dissolve",
  "ADBE Gradient Wipe",
  "ADBE Linear Wipe",
  "ADBE Radial Wipe",
  "ADBE Venetian Blinds",
  "ADBE Roughen Edges",
  "ADBE Color Emboss",
  "ADBE Emboss",
  "ADBE Corner Pin",
  "ADBE Fast Blur", // fast blur legacy
  "ADBE Spherize",
  "ADBE Turbulent Displace",
  "ADBE Wave Warp",
  "ADBE Geometry2", // transform
  "ADBE Twirl",
  "ADBE Magnify",
  "ADBE Mirror",
  "ADBE Arithmetic",
  "ADBE Checkerboard",
  "ADBE Ramp",
  "ADBE 4ColorGradient",
  "ADBE Posterize Time",
  "ADBE Circle",
  "ADBE CHANNEL MIXER",
  "ADBE Grid",
  "ADBE Paint Bucket",
  "ADBE Set Matte3",
  "ADBE Tile",
];
